title: Your awesome title
author: Leonardo!!
email: leonardo@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Description
  Bla bla bla
  
  Sub-desc
  Bla bla bla

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
facebook_username:  your-faeebook-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
